version: '3.8'

services:
  database:
    image: postgres:15
    restart: always
    volumes:
      - calcom-database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-calcom}
    networks:
      - calcom-stack

  calcom:
    image: ghcr.io/merteraslan/calcom:latest
    restart: always

    environment:
      # Database connection
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@database:5432/${POSTGRES_DB:-calcom}
      DATABASE_DIRECT_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@database:5432/${POSTGRES_DB:-calcom}
      DATABASE_HOST: database

      # App Config
      NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
      NEXT_PUBLIC_API_V2_URL: ${NEXT_PUBLIC_API_V2_URL}
      NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
      NEXT_PUBLIC_WEBSITE_TERMS_URL: ${NEXT_PUBLIC_WEBSITE_TERMS_URL}
      NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL: ${NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL}
      CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
      NODE_ENV: production
    labels:
      - traefik.enable=true
      - traefik.http.routers.calcom.rule=Host(`calcom.voxvol.com`)
      - traefik.http.routers.calcom.entrypoints=https
      - traefik.http.routers.calcom.tls=true
      - traefik.http.routers.calcom.tls.certresolver=letsencrypt
      - traefik.http.services.calcom.loadbalancer.server.port=3000
    networks:
      - calcom-stack
      - coolify

volumes:
  calcom-database-data:


networks:
  calcom-stack:
  coolify:
    external: true
